package claudeingest

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/galois-labs/edge/internal/config"
	"github.com/galois-labs/edge/internal/installid"
)

// UserStateDir returns the per-user state directory for Claude ingestion.
// The path follows the daemon's existing UserConfigDir convention rather
// than os.UserConfigDir() to stay consistent with where the rest of the
// daemon's user-scoped state lives (~/.config/galois-edge on Unix,
// %APPDATA%\galois-edge on Windows).
func UserStateDir() (string, error) {
	return filepath.Join(config.UserConfigDir(), "claude-ingest"), nil
}

// ConsentPath returns the local consent JSON path.
func ConsentPath() (string, error) {
	dir, err := UserStateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "consent.json"), nil
}

// OffsetsPath returns the local transcript offset JSON path.
//
// Deprecated: use AnchorsPath. Kept as an alias because legacy callers
// in hook.go and backfill.go still reference it. After the resume and
// backfill rewrites land, this function is removable.
func OffsetsPath() (string, error) {
	return AnchorsPath()
}

// LocalSubject returns the stable local consent subject for the current
// user. The key is derived as sha256(install_id || "\x00" || os_user)
// per the v2 spec; install_id is the per-machine UUID generated by the
// daemon at first registration (with a per-user fallback when the system
// file is unavailable). The raw install_id is intentionally not included
// in the Subject — only the hash and human-readable metadata.
func LocalSubject() (Subject, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Subject{}, err
	}
	hostname, _ := os.Hostname()

	osUser := os.Getenv("USER")
	if osUser == "" {
		osUser = os.Getenv("USERNAME")
	}
	if osUser == "" {
		if u, err := user.Current(); err == nil {
			osUser = u.Username
		}
	}
	if osUser == "" {
		osUser = "unknown"
	}

	id, err := installid.Ensure()
	if err != nil {
		return Subject{}, fmt.Errorf("install id: %w", err)
	}
	keyInput := strings.Join([]string{id, osUser}, "\x00")
	sum := sha256.Sum256([]byte(keyInput))
	return Subject{
		Key:      hex.EncodeToString(sum[:]),
		OSUser:   osUser,
		Hostname: hostname,
		HomeDir:  home,
	}, nil
}

// NormalizeFolders converts user-provided folder arguments into absolute,
// deduplicated paths. Paths do not need to exist; this allows enabling before a
// project checkout is created, but still stores a deterministic absolute scope.
func NormalizeFolders(folders []string) ([]string, error) {
	if len(folders) == 0 {
		return nil, fmt.Errorf("at least one folder is required")
	}

	seen := make(map[string]bool, len(folders))
	out := make([]string, 0, len(folders))
	for _, f := range folders {
		f = strings.TrimSpace(f)
		if f == "" {
			continue
		}
		if strings.HasPrefix(f, "~") {
			home, err := os.UserHomeDir()
			if err != nil {
				return nil, err
			}
			if f == "~" {
				f = home
			} else if strings.HasPrefix(f, "~/") || strings.HasPrefix(f, `~\`) {
				f = filepath.Join(home, f[2:])
			}
		}
		abs, err := filepath.Abs(f)
		if err != nil {
			return nil, err
		}
		abs = filepath.Clean(abs)
		key := normalizePathForCompare(abs)
		if !seen[key] {
			seen[key] = true
			out = append(out, abs)
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("at least one folder is required")
	}
	sort.Strings(out)
	return out, nil
}

// IsPathAllowed reports whether cwd is exactly an allowed folder or beneath
// one. It never treats sibling prefixes as matches.
func IsPathAllowed(cwd string, allowed []string) bool {
	if cwd == "" {
		return false
	}
	abs, err := filepath.Abs(cwd)
	if err != nil {
		return false
	}
	cwdKey := normalizePathForCompare(filepath.Clean(abs))
	for _, folder := range allowed {
		folderAbs, err := filepath.Abs(folder)
		if err != nil {
			continue
		}
		folderKey := normalizePathForCompare(filepath.Clean(folderAbs))
		if cwdKey == folderKey {
			return true
		}
		prefix := folderKey
		if !strings.HasSuffix(prefix, string(filepath.Separator)) {
			prefix += string(filepath.Separator)
		}
		if strings.HasPrefix(cwdKey, prefix) {
			return true
		}
	}
	return false
}

func normalizePathForCompare(path string) string {
	if runtime.GOOS == "windows" {
		return strings.ToLower(path)
	}
	return path
}

// LoadConsent reads local consent. os.ErrNotExist means not configured.
func LoadConsent() (*Consent, error) {
	path, err := ConsentPath()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var consent Consent
	if err := json.Unmarshal(data, &consent); err != nil {
		return nil, err
	}
	return &consent, nil
}

// SaveConsent writes local consent with user-only permissions.
func SaveConsent(consent Consent) error {
	path, err := ConsentPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(consent, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0o600)
}
